# Generated by Django 2.1.5 on 2019-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(verbose_name='Data da consulta'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='cod_exame',
            field=models.IntegerField(verbose_name='Codigo do exame '),
        ),
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.CharField(max_length=120, verbose_name='Descrição do exame'),
        ),
        migrations.AlterField(
            model_name='examerealizado',
            name='valor_exame',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Valor do exame'),
        ),
    ]
